# Generated by Django 5.0.3 on 2024-04-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exercset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercset',
            old_name='exercep',
            new_name='exercminrep',
        ),
        migrations.CreateModel(
            name='Protocolo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercset')),
            ],
        ),
    ]
