# Generated by Django 5.0.3 on 2024-04-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_exercep_exercset_exercminrep_protocolo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo1',
            name='exerc',
        ),
        migrations.AddField(
            model_name='protocolo1',
            name='exerc',
            field=models.ManyToManyField(to='main.exercset'),
        ),
    ]
