# Generated by Django 5.0.3 on 2024-04-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_protocolo1_exerc_protocolo1_exerc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercset',
            name='exercname',
        ),
        migrations.AddField(
            model_name='exercset',
            name='exercname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
