# Generated by Django 5.0.3 on 2024-04-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_registros'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='Ficha',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registros',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
