# Generated by Django 5.0.3 on 2024-04-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_registros_ficha_alter_registros_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercparam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField(default=3, null=True)),
                ('repetmin', models.IntegerField(default=10, null=True)),
                ('repetmax', models.IntegerField(default=12, null=True)),
                ('pesomin', models.IntegerField(null=True)),
                ('nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.exercname')),
            ],
        ),
        migrations.CreateModel(
            name='Fichaname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Protocolo01',
        ),
        migrations.DeleteModel(
            name='Protocolo02',
        ),
        migrations.DeleteModel(
            name='Protocolo03',
        ),
        migrations.DeleteModel(
            name='Protocolo04',
        ),
        migrations.DeleteModel(
            name='Registros',
        ),
        migrations.AddField(
            model_name='exercparam',
            name='ficha',
            field=models.ManyToManyField(to='main.fichaname'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.exercname')),
                ('data', models.DateTimeField(auto_now=True, null=True)),
                ('peso', models.IntegerField(null=True)),
                ('ficha', models.ManyToManyField(to='main.fichaname')),
            ],
        ),
    ]
