# Generated by Django 5.0.3 on 2024-04-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_registros_ficha_alter_registros_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='registros',
            name='Ficha',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='peso2',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='peso3',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='peso4',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='peso5',
        ),
        migrations.RemoveField(
            model_name='registros',
            name='peso6',
        ),
        migrations.AddField(
            model_name='registros',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo01',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo02',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo03',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo04',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.exercicios'),
        ),
    ]
