# Generated by Django 5.0.3 on 2024-04-05 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exercname_exercparam_fichaname_delete_protocolo01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercparam',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='log',
            name='name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='ficha',
        ),
        migrations.AddField(
            model_name='exercparam',
            name='exerc',
            field=models.CharField(default='Exercicio desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='exerc',
            field=models.ForeignKey(default='Exercicio desconhecido', on_delete=django.db.models.deletion.CASCADE, to='main.exercparam'),
        ),
        migrations.AddField(
            model_name='log',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='exercparam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='exercparam',
            name='pesomin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercparam',
            name='repetmax',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='exercparam',
            name='repetmin',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichaname',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Exercname',
        ),
    ]
