# Generated by Django 5.0.3 on 2024-04-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exercicios_ficha_remove_registros_ficha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registros',
            name='exercname',
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo01',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo02',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo03',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercicios'),
        ),
        migrations.AlterField(
            model_name='protocolo04',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercicios'),
        ),
    ]
