# Generated by Django 5.0.3 on 2024-04-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exercparam_fichaname_log_delete_protocolo01_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercparametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('serie', models.IntegerField(default=3, null=True)),
                ('repetmin', models.IntegerField(blank=True, default=10, null=True)),
                ('repetmax', models.IntegerField(blank=True, default=12, null=True)),
                ('pesomin', models.IntegerField(blank=True, null=True)),
                ('ficha', models.ManyToManyField(to='main.fichaname')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='exerc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercparametros'),
        ),
        migrations.DeleteModel(
            name='Exercparam',
        ),
    ]
