# Generated by Django 5.0.3 on 2024-04-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_exercparam_nome_remove_log_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='exerc',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.exercparam'),
        ),
    ]
