# Generated by Django 5.0.3 on 2024-04-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_registros_exercname_alter_exercicios_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='exercname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercicios'),
        ),
    ]
