# Generated by Django 5.0.3 on 2024-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_exercparametros_id_alter_fichaname_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercparametros',
            name='pesomax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='log',
            name='exerc',
        ),
        migrations.AddField(
            model_name='log',
            name='exerc',
            field=models.ManyToManyField(to='main.exercparametros'),
        ),
    ]
