# Generated by Django 5.0.3 on 2024-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_exercparametros_pesomax_remove_log_exerc_log_exerc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercparametros',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
