# Generated by Django 5.0.3 on 2024-04-07 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_exercparametros_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercparametros',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
